=== Elijah99/FourthTask/src/test/resources/tariffs.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs" elementFormDefault="qualified">
    <element name="tariff" type="tns:Tariff"/>
    <element name="tariff-with-internet" type="tns:TariffWithInternet" substitutionGroup="tns:tariff"/>
    <element name="tariffs">
        <complexType>
            <sequence>
                <element name="tariff" type="tns:Tariff" minOccurs="1" maxOccurs="unbounded"/>
                <element name="tariff-with-internet" type="tns:TariffWithInternet" minOccurs="0" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="CallPrices">
        <sequence>
            <element name="same-operator" type="float"/>
            <element name="another-operator" type="float"/>
            <element name="landline-phones" type="float"/>
        </sequence>
    </complexType>
    <complexType name="Tariff">
        <sequence>
            <element name="id" type="integer"/>
            <element name="name" type="string"/>
            <element name="operator-name" type="string"/>
            <element name="payroll" type="float"/>
            <element name="sms-price" type="float"/>
            <element name="call-prices" type="tns:CallPrices"/>
        </sequence>
    </complexType>
    <complexType name="TariffWithInternet">
        <complexContent>
            <extension base="tns:Tariff">
               <sequence>
                   <element name="traffic-in-megabyte" type="float"/>
                   <element name="price-for-one-megabyte" type="float"/>
                   <element name="is-modem-mode-enabled" type="boolean"/>
               </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== Elijah99/FourthTask/src/test/resources/tariffs_valid_data.xml
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/tariffs"
         xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">
    <tariff>
        <id>0</id>
        <name>name</name>
        <operator-name>operator</operator-name>
        <payroll>0.00</payroll>
        <sms-price>0.00</sms-price>
        <call-prices>
            <same-operator>0.00</same-operator>
            <another-operator>0.00</another-operator>
            <landline-phones>0.00</landline-phones>
        </call-prices>
    </tariff>
    <tariff>
        <id>1</id>
        <name>name1</name>
        <operator-name>operator1</operator-name>
        <payroll>1.11</payroll>
        <sms-price>1.11</sms-price>
        <call-prices>
            <same-operator>1.11</same-operator>
            <another-operator>1</another-operator>
            <landline-phones>1</landline-phones>
        </call-prices>
    </tariff>
    <tariff>
        <id>2</id>
        <name>name2</name>
        <operator-name>operator2</operator-name>
        <payroll>2.22</payroll>
        <sms-price>2.22</sms-price>
        <call-prices>
            <same-operator>2.22</same-operator>
            <another-operator>2.22</another-operator>
            <landline-phones>2.22</landline-phones>
        </call-prices>
    </tariff>
    <tariff-with-internet>
        <id>3</id>
        <name>name3</name>
        <operator-name>operator3</operator-name>
        <payroll>3.33</payroll>
        <sms-price>3.33</sms-price>
        <call-prices>
            <same-operator>3.33</same-operator>
            <another-operator>3.33</another-operator>
            <landline-phones>3.33</landline-phones>
        </call-prices>
        <traffic-in-megabyte>333</traffic-in-megabyte>
        <price-for-one-megabyte>3</price-for-one-megabyte>
        <is-modem-mode-enabled>true</is-modem-mode-enabled>
    </tariff-with-internet>
    <tariff-with-internet>
        <id>4</id>
        <name>name4</name>
        <operator-name>operator4</operator-name>
        <payroll>4.44</payroll>
        <sms-price>4</sms-price>
        <call-prices>
            <same-operator>4</same-operator>
            <another-operator>4.44</another-operator>
            <landline-phones>4.44</landline-phones>
        </call-prices>
        <traffic-in-megabyte>444.4</traffic-in-megabyte>
        <price-for-one-megabyte>44.4</price-for-one-megabyte>
        <is-modem-mode-enabled>false</is-modem-mode-enabled>
    </tariff-with-internet>
</tariffs>

=== Elijah99/FourthTask/src/test/resources/tariffs.xml
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/tariffs"
         xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">
    <tariff>
        <id>1</id>
        <name>name</name>
        <operator-name>operator</operator-name>
        <payroll>3.15</payroll>
        <sms-price>0.22</sms-price>
        <call-prices>
            <same-operator>1.22</same-operator>
            <another-operator>3.22</another-operator>
            <landline-phones>5.22</landline-phones>
        </call-prices>
    </tariff>
</tariffs>
